server:
  port: 8092
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
    mvc:
      static-path-pattern: /files/**

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: gkuer
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true


  h2:
    console:
      enabled: true

  # Springboot 2.6 - Swagger 충돌 fix
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
